VS code push

diff --git a/functions_KD b/functions_KD
--- a/functions_KD
+++ b/functions_KD
@@ -1,5 +1,43 @@
 # User-specific functions
-#
+
+# Function returns path of file in which a given function name is defined
+whichfunc () (
+	# $1 is function name input or help option
+	if (( $# < 1  )) || (( $# > 2 )) || [[ $1 == "-h" ]] || \
+[[ $1 == "--help" ]]
+	then
+		echo \
+"Function returns path of file in which a given function name is defined
+
+Usage: whichfunc [-h / --help] <function name> 
+
+Options:
+-h, --help : Prints this help message"
+	else
+		shopt -s extdebug
+		declare -F "$1"
+	fi
+)
+
+
+# Function returns partition names with idle nodes
+whosopen () {
+	# $1 can be help option
+	if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
+	then
+		echo \
+"Function returns names of parititons with currently idle nodes.
+
+Usage: whosopen [-h / --help]
+
+Options:
+-h, --help : Prints this help message"
+	else
+		sinfo | grep "idle" | awk '{print $1}'
+	fi
+}
+
+
 # Function to quickly push changes to GitHub from remote git repo
 gitpublish() {
 	# $1 is the commit message
@@ -9,7 +47,7 @@ gitpublish() {
 [[ $1 == "--help" ]]
 	then
 		echo \
-"$# options given to gitpublish: $@
+"$# options given to gitpublish: $*
 
 Function pushes repository to GitHub with commit message specified by 
 <commit_msg>. If target repository is not the current directory, specify 
@@ -32,36 +70,60 @@ Usage: gitpublish <commit_msg> [/path/to/repo]"
 }
 
 
-# Function to get job info from SLURM "sacct" for a specific
+# Generate YYYY-MM-DD formatted date from 10 years prior to today
+olddate () {
+	date -d "10 years ago" +%F
+}
+
+
+# Function to get job info from Slurm "sacct" for a specific
 # job name and start date
 getjobinfo () {
 	# $1 is the job name
 	# $2 is the start date 
-	# (prints info for all jobs starting on 'date' at 00:00:00)
-	# accepted input format for --starttime: YYYY-MM-DD[THH:MM[:SS]]
+	# Returns info for all jobs starting after <startdate> (format YYYY-MM-DD)
 	# Help message
+	local hlp="Function prints most informative outputs of Slurm 'sacct' for
+given job name and start date.
+
+Usage: getjobinfo <job_name> <start_date>
+
+The format of <start_date> must be: YYYY-MM-DD."
+	# Format string
+	fmt="JobID%20,JobName,State,ExitCode,Start,End,Elapsed,CPUTime,ReqMem,MaxRSS,NCPUS"
 	if (( $# < 2 )) || [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
 	then
-		echo \
-"Function prints most informative outputs of SLURM 'sacct' for given job name 
-and start date.
-
-Usage: getjobinfo <job_name> <start_date>
-
-The format of <start_date> must be: YYYY-MM-DD.
-Automatically starts at 00:00:00 on <start_date>."
+		echo "$hlp"
 	elif [[ -z $2 ]]
 	then
-		echo \
-"Missing <start_date>.
-
-Usage: getjobinfo <job_name> <start_date>
-
-The format of <start_date> must be: YYYY-MM-DD.
-Automatically starts at 00:00:00 on <start_date>."
+		echo "Missing <start_date>."
+		echo "$hlp"
 	else
-		sacct --format="JobID%20,JobName,State,ExitCode,Start,End,\
-Elapsed,CPUTime,ReqMem,MaxRSS,NCPUS" --name "$1" --starttime "${2}T00:00:00"
+		sacct --format="$fmt" --name "$1" -S "$2"
+	fi
+}
+
+# Function to get tab-separated list of job IDs from Slurm from given job name
+# Retrieves all IDs (start date arbitrarily set to 10 years ago)
+getjobids () {
+	# Help message
+	local hlp="Function to list all job IDs returned by Slurm 'sacct' for a
+specific job name. Excludes job IDs ending in '.batch' or '.extern'.
+
+Usage: getjobids <job_name>
+
+Automatically starts at 10 years prior to today's date (e.g., $start_date)."
+	if (( $# < 1 )) || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
+	then
+		echo "$hlp"
+	else
+		# sacct -n -o jobid%50 --name "$1" -S "$(olddate)"
+		sacct --format "JobID%20,State%20" --name "$1" -S "$(olddate)" | \
+		# Retrieve only IDs for completed or out of memory jobs,
+		# excluding x.batch and x.extern job IDs
+		grep "COMPLETED" | grep -v "batch\|extern" | awk '{print $1}'
+		# # Substitute newlines with commas and trim trailing comma
+		# tr -s '\n' ',' | tr -d '[:space:]' | sed 's/\(.*\),/\1/'
 	fi
 }
 
@@ -69,155 +131,206 @@ Elapsed,CPUTime,ReqMem,MaxRSS,NCPUS" --name "$1" --starttime "${2}T00:00:00"
 # Function to list the max memory usage (MaxRSS) for each job for 
 # a specific job name
 jobmem () {
-	start_date=$(date -d "1 year ago" +%F)
 	# Help message
-	if (( $# < 2 )) || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
+	local hlp="Function to list the max memory usage (MaxRSS) for each job
+listed by Slurm 'sacct' for a specific job name, sorted from least to greatest.
+
+Usage: jobmem <job_name>
+
+Automatically starts at 10 years prior to today's date (e.g., $start_date)."
+	if (( $# < 1 )) || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
 	then
-		echo \
-"Function to list or find the maximum of the max memory usage (MaxRSS) for 
-each job listed by SLURM 'sacct' for a specific job name over the last year.
-
-Usage: jobmem <option> <job_name>
-Options:
-  -m, --max:	return only the highest MaxRSS value for jobs with <job_name>
-  -l, --list:	list MaxRSS values for jobs with <job_name> in human-readable
-		format (e.g., KB/MB/GB)
-
-Automatically starts at 00:00:00 1 year prior to today's date ($start_date)."
-	elif [[ $1 = "--max" ]] || [[ $1 = "-m" ]] || \
-[[ $1 = "-l" ]] || [[ $1 = "--list" ]]
-	then
-		jobids=$(getjobinfo $2 $start_date | grep "batch" | \
-grep "COMPLETED\|OUT_OF_ME" | awk '{print $1}')
-		rss=$(getjobinfo $2 $start_date | grep "batch" | \
-grep "COMPLETED\|OUT_OF_ME" | awk '{print $9}')
-		jobids=(${jobids// / })
-		rss=(${rss// / })
-		cnt=${#jobids[@]}
-		max_m=0
-		for ((i=0;i<cnt;i++))
-		do
-			j=${jobids[i]}
-			# Remove unit and decimals
-			m=`echo ${rss[i]} | sed 's/[A-Z.].*//g'`
-			# Save unit
-			m_unit=`echo ${rss[i]} | sed 's/[[:digit:].]*//g'`
-			if [[ $1 = "--max" ]] || [[ $1 = "-m" ]]
-			then
-				[[ $m_unit = "M" ]] && m=$(( $m / 1000 ))
-				if (( $m > $max_m ))
-				then
-					max_j=$j; max_m=$m; max_m_unit=$m_unit
-				fi
-			fi
-			[[ $max_m ]] && (( $max_m != 0 )) && [[ $max_m_unit ]] \
-&& m=$max_m && m_unit=$max_m_unit
-			# Handles input in kilobytes (KB)
-			if [[ $m_unit = "K" ]]
-			then
-				if (( `echo -n $m | wc -c` < 4 ))
-				then
-					mem="${m}KB"
-				elif (( `echo -n $m | wc -c` < 7 ))
-				then
-					mem="$(( $m / 1000 ))MB"
-				else
-					mem="$(( $m / 1000000 ))GB"
-				fi
-			# Handles input in megabytes (MB)
-			elif [[ $m_unit = "M" ]]
-			then
-				if (( `echo -n $m | wc -c` < 3 ))
-				then
-					mem="${m}MB"
-				else
-					mem="$(( $m / 1000 ))GB"
-				fi
-			else
-				echo \ 
-"Error - unrecognized unit of memory in ${m}: ${m_unit}.
-
-Check output of 'MaxRSS' column from command 'getjobinfo $2 $start_date'.
-This function only handes K and M unit inputs."
-				break
-			fi
-			if [[ $1 = "--list" ]] || [[ $1 = "-l" ]]
-			then
-				printf "%s\t%s\n" "${j}" "${mem}"
-			fi
-		done
-		if [[ $1 = "--max" ]] || [[ $1 = "-m" ]]
-		then
-			printf "%s\t%s\n" "${max_j}" "${mem}"
-		fi
-		unset -v jobids rss cnt i j max_j m max_m max_m_unit mem
+		echo "$hlp"
 	else
-		echo "Error - unrecognized option: ${1}. Use the -h/--help \
-flag for more information."
+		local ids
+		mapfile -t ids < <(getjobids "$1")
+		for ((i=0;i<${#ids[@]};i++))
+		do
+			local id="${ids[i]}"
+			local mem
+			mem="$(jobinfo "$id" | grep "Max memory" | awk -F' : ' '{print $2}')"
+			# Remove '(estimate)' ending
+			mem="${mem%% *}"
+			# Remove whitespace
+			mem="$(echo "$mem" | tr -d ' ')"
+			printf "%s\t%s\n" "$mem" "$id"
+		done | sort -h
 	fi
 }
 
 
 # Function to list elapsed time in seconds for each job listed by 
-# SLURM 'sacct' for a specific job name
+# Slurm 'sacct' for a specific job name
 jobtime () {
-	start_date=$(date -d "1 year ago" +%F)
+	local start_date="$(olddate)"
+	local hlp="Function to list elapsed times (Elapsed) for each job listed by
+Slurm 'sacct' for a specific job name, sorted from least to greatest.
+
+Usage: jobtime <job_name>
+
+Automatically starts 10 years prior to today's date (e.g., $start_date)."
+	if (( $# < 1 )) || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
+	then
+		echo "$hlp"
+	else
+		local ids
+		mapfile -t ids < <(getjobids "$1")
+		for ((i=0;i<${#ids[@]};i++))
+		do
+			local id="${ids[i]}"
+			local t
+			t="$(jobinfo "$id" | grep "Used walltime" | awk -F' : ' '{print $2}')"
+			# Remove whitespace
+			t="$(echo "$t" | tr -d ' ')"
+			printf "%s\t%s\n" "$t" "$id"
+		done | sort -h
+	fi
+}
+
+# Function to list the max memory usage (MaxRSS) for each job for 
+# a specific job name (can also calculate maximum)
+jobmem2 () {
+	local start_date="$(olddate)"
+	# Help message
+	local hlp="Function to list or find the maximum of the max memory usage (MaxRSS) for 
+each job listed by Slurm 'sacct' for a specific job name over the last 10 years.
+
+Usage: jobmem2 <option> <job_name>
+Options:
+  -m	return only the highest MaxRSS value for jobs with <job_name>
+  -l	list MaxRSS values for jobs with <job_name> in human-readable
+		format (e.g., KB/MB/GB)
+
+Automatically starts at 10 years prior to today's date (e.g., $start_date)."
 	if (( $# < 2 )) || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
 	then
-		echo \
-"Function to list or find the maximum of elapsed times (Elapsed) for each
-job listed by SLURM 'sacct' for a specific job name over the year.
-
-Usage: jobtime [option] <job_name>
-Options:
-  -m, --max:    return only greatest Elapsed time for jobs with <job_name>
-  -l, --list:   list all Elapsed time values for jobs with <job_name> in
-                seconds format
-
-Automatically starts at 00:00:00 1 year prior to today's date ($start_date)."
-	elif [[ $1 = "--max" ]] || [[ $1 = "-m" ]] || \
-[[ $1 = "-l" ]] || [[ $1 = "--list" ]]
+		echo "$hlp"
+	elif [[ $1 = "-m" ]] || [[ $1 = "-l" ]]
 	then
-		# Take  JobID and Elapsed columns from ony completed batch jobs
-		jobids=`getjobinfo $2 $start_date | grep "batch" | \
-grep "COMPLETED\|OUT_OF_ME" | awk '{print $1}'`
-		elapsed=`getjobinfo $2 $start_date | grep "batch" | \
-grep "COMPLETED\|OUT_OF_ME" | awk '{print $7}'`
-		jobids=(${jobids// / })
-		elapsed=(${elapsed// / })
-		cnt=${#jobids[@]}
-		max_t=0
+		local jobres=$(getjobinfo "$2" "$start_date" | grep "batch" | grep "COMPLETED\|OUT_OF_ME")
+		local jobids=$(echo "$jobres" | awk '{print $1}')
+		local rss=$(echo "$jobres" | awk '{print $9}')
+		local jobids=(${jobids// / })
+		local rss=(${rss// / })
+		local cnt="${#jobids[@]}"
+		local max_m=0
 		for ((i=0;i<cnt;i++))
 		do
-			j=${jobids[i]}
-			t=`echo "${elapsed[i]}" | awk -F: '{ print ($1 * 3600) \
-+ ($2 * 60) + $3 }'`
-			if [[ $1 = "--list" ]] || [[ $1 = "-l" ]]
+			local j=${jobids[i]}
+			# Remove unit and decimals
+			local m="$(echo "${rss[i]}" | sed 's/[A-Z.].*//g')"
+			# Save unit
+			local m_unit=$(echo ${rss[i]} | sed 's/[[:digit:].]*//g')
+			if [[ $1 = "-m" ]]
 			then
-				printf "%s\t%s\n" "${j}" "${t} seconds"
-			elif [[ $1 = "--max" ]] || [[ $1 = "-m" ]]
-			then
-				if (( $t > $max_t ))
+				[[ $m_unit = "M" ]] && local m=$(( m / 1000 ))
+				if (( m > max_m ))
 				then
-					max_j=$j; max_t=$t
+					local max_j=$j
+					local max_m=$m
+					local max_m_unit=$m_unit
 				fi
 			fi
-		done
-		if [[ $1 = "--max" ]] || [[ $1 = "-m" ]]
-		then
-			printf "%s\t%s\n" "${max_j}" "${max_t} seconds"
-			if (( $max_t >= 3600 ))
+			if [[ $max_m ]] && (( max_m != 0 )) && [[ $max_m_unit ]]
 			then
-				printf "\t\t%s\n" "~$(( $max_t / 3600 )) hours"
-			elif (( $max_t < 3600 ))
-			then
-				printf "\t\t%s\n" "~$(( $max_t / 60 )) minutes"
+				local m=$max_m
+				local m_unit=$max_m_unit
 			fi
+			# Handles input in kilobytes (KB)
+			if [[ $m_unit = "K" ]]
+			then
+				if (( $(echo -n "$m" | wc -c) < 4 ))
+				then
+					local mem="${m}KB"
+				elif (( $(echo -n "$m" | wc -c) < 7 ))
+				then
+					local mem="$((m / 1000))MB"
+				else
+					local mem="$((m / 1000000))GB"
+				fi
+			# Handles input in megabytes (MB)
+			elif [[ $m_unit = "M" ]]
+			then
+				if (( $(echo -n "$m" | wc -c) < 3 ))
+				then
+					local mem="${m}MB"
+				else
+					local mem="$((m / 1000))GB"
+				fi
+			else
+				# Error message
+				local err="Error - unrecognized unit of memory in ${m}: ${m_unit}.
+
+Check output of 'MaxRSS' column from command 'getjobinfo $2 $start_date'.
+This function only handes K and M unit inputs."
+				echo "$err"
+				break
+			fi
+			if [[ $1 = "-l" ]]
+			then
+				printf "%s\t%s\n" "${j}" "${mem}"
+			fi
+		done
+		if [[ $1 = "-m" ]]
+		then
+			printf "%s\t%s\n" "${max_j}" "${mem}"
 		fi
-		unset -v jobids elapsed cnt i t max_t j max_j
 	else
-		echo "Error - unrecognized option: ${1}. Use the -h/--help \
-flag for more information."
+		echo "Error, unrecognized option: ${1}. Run jobmem -h/--help for help."
+	fi
+}
+
+
+# Function to list elapsed time in seconds for each job listed by 
+# Slurm 'sacct' for a specific job name
+jobtime2 () {
+	local start_date="$(olddate)"
+	local hlp="Function to list or find the maximum of elapsed times (Elapsed) for each
+job listed by Slurm 'sacct' for a specific job name over the last 10 years.
+
+Usage: jobtime2 [option] <job_name>
+Options:
+  -m    return only greatest Elapsed time for jobs with <job_name>
+  -l    list all Elapsed time values for jobs with <job_name>
+
+Automatically starts 10 years prior to today's date (e.g., $start_date)."
+	if (( $# < 2 )) || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
+	then
+		echo "$hlp"
+	elif [[ $1 = "-m" ]] || [[ $1 = "-l" ]]
+	then
+		# Take  JobID and Elapsed columns from ony completed batch jobs
+		local jobres=$(getjobinfo $2 $start_date | grep "batch" | grep "COMPLETED\|OUT_OF_ME")
+		local jobids=$(echo "$jobres" | awk '{print $1}')
+		local elapsed=$(echo "$jobres" | awk '{print $7}')
+		local jobids=(${jobids// / })
+		local elapsed=(${elapsed// / })
+		local cnt="${#jobids[@]}"
+		local max_t=0
+		for ((i=0;i<cnt;i++))
+		do
+			local j=${jobids[i]}
+			local t=$(echo "${elapsed[i]}" | awk -F: '{print ($1 * 3600) + ($2 * 60) + $3}')
+			if [[ $1 = "-l" ]]
+			then
+				((t >= 3600)) && local read_t="($((t/3600)) hours)"
+				((t < 3600)) && local read_t="($((t/60)) minutes)"
+				((t < 60)) && unset -v read_t
+				echo "$j	$t seconds $read_t"
+			elif [[ $1 = "-m" ]]
+			then
+				(( t > max_t )) && { max_j=$j; max_t=$t; }
+			fi
+		done
+		if [[ $1 = "-m" ]]
+		then
+			((max_t >= 3600)) && local max_read_t="($((max_t/3600)) hours)"
+			((max_t < 3600)) && local max_read_t="($((max_t/60)) minutes)"
+			((max_t < 60)) && unset -v max_read_t
+			echo "$max_j	$max_t seconds $max_read_t"
+		fi
+	else
+		echo "Error, unrecognized option: ${1}. Run jobtime -h/--help for help."
 	fi
 }
 
